name: bookhub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.16
  image_picker: ^0.8.7+4
  # flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.14.1
  flutter_rating_bar: ^4.0.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  js: ^0.6.7

# flutter_native_splash:
#   color: "#FFFFFF" # Warna latar belakang
#   image: images/splash.png # Gambar logo
#   android: true
#   ios: true
#   web: true
#   fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/book_images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
